### ISSUE TITLE
Cannot install in a clean virtualenv

### ISSUE THREAD

**Issue by ecederstrand** [iseekwonderful/PyPathway#2]
A Python package should always be able to install itself in an empty virtualenv and handle dependencies automatically. Trying to do this with PyPathway fails:

```bash
$ git clone https://github.com/iseekwonderful/PyPathway.git
$ cd PyPathway
$ python3 -m venv build_env
$ source build_env/bin/activate
$ python3 -m pip install -e .
Obtaining file:///opt/repos/PyPathway
    ERROR: Command errored out with exit status 1:
     command: /opt/repos/PyPathway/build_env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/repos/PyPathway/setup.py'"'"'; __file__='"'"'/opt/repos/PyPathway/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /opt/repos/PyPathway/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/repos/PyPathway/setup.py", line 8, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This is because `numpy` is imported before the `install_requires` directive has a chance to install it.

**Comment by ecederstrand** [comment]
@iseekwonderful Ping?

**Comment by ecederstrand** [comment]
No longer using this package. Closing.
